# List of dependencies of the project

[versions]
coroutines = "1.7.3"
prepared = "0.6.0"

[plugins]

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
prepared-kotest = { module = "dev.opensavvy.prepared:runner-kotest", version.ref = "prepared" }

[bundles]
